config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /ru|en/ do 
    root 'users#index'
    
    devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
    telegram_webhook TelegramWebhooksController

    resources :users, only: %i[show] do
      resources :connections, except: %i[index show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_one :connection, dependent: :destroy
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates :tg_token, :chat_id, :site, :email, :api_token, :project_key, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :jira_project_exists, :bot_connected

  def jira_project_exists
    options = {
      username:     email,
      password:     api_token,
      site:,
      context_path: '',
      auth_type:    :basic
    }
    client = JIRA::Client.new(options)

    begin
      client.Project.find(project_key)
    rescue JIRA::HTTPError
      errors.add(:base, message: I18n.t('models.connection.connection_error'))
    rescue StandardError
      errors.add(:base, message: I18n.t('models.connection.unknown_error'))
    end
  end

  def bot_connected
    Telegram.bot.get_me
  rescue Telegram::Bot::Error
    errors.add(:base, message: I18n.t('models.connection.bot_connection_error'))
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :connections, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  protected

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def default_url_options
    if I18n.locale == I18n.default_locale
      { locale: nil }
    else
      { locale: I18n.locale }
    end
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :find_user
  before_action :set_connection, only: %i[edit update destroy]
  before_action :set_chats_collection, only: %i[new create edit update]

  def new
    @connection = @user.connections.new
  end

  def create
    @connection = @user.connections.new(connection_params)
    @connection.tg_token = Telegram.bot.token

    if @connection.save
      flash[:notice] = t('connections.new.success')
      connection_bot_notification(@connection, true)
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @connection.update(connection_params)
      flash[:notice] = t('connections.new.success')
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @connection.destroy
    connection_bot_notification(@connection, false)
    redirect_to user_path(@user)
  end

  private

  def connection_bot_notification(connection, status)
    action = status ? 'connected' : 'disconnected'
    I18n.with_locale(:bot) do
      Telegram.bot.send_message chat_id: connection.chat_id,
                                text:    t(action, key: connection.project_key)
    end
  end

  def set_chats_collection
    @chats_collection = Chat.left_joins(:connection).where(connection: { chat_id: [nil, @connection&.chat_id].uniq })
  end

  def set_connection
    @connection = Connection.find(params[:id])
  end

  def find_user
    @user = User.find(params[:user_id])
    redirect_to user_path(current_user) unless @user == current_user
  end

  def connection_params
    params.require(:connection).permit(:chat_id, :site, :email, :api_token, :project_key)
  end
end

app/controllers/telegram_webhooks_controller.rb
class TelegramWebhooksController < Telegram::Bot::UpdatesController
  I18n.locale = 'bot'

  # adding bot to a new group
  def my_chat_member(my_chat_member)
    if my_chat_member.dig('new_chat_member', 'status') == 'member'
      respond_with :message, text: t('chat_invite')

      Chat.create(id: my_chat_member.dig('chat', 'id'), title: my_chat_member.dig('chat', 'title'))
    end
    Chat.find(my_chat_member.dig('chat', 'id')).destroy if my_chat_member.dig('new_chat_member', 'status') == 'left'
  end

  # request to create issue
  def message(message)
    change_title(message) unless message['new_chat_title'].nil?
    return if message['text'].nil?
    return unless message['text'].start_with?("@#{Telegram.bot.username}")

    if message.dig('chat', 'type') == 'private'
      respond_with :message, text: t('private_mention')
      return
    end

    response = IssueCreator.call(message)
    reply_with :message, text: response[:message], parse_mode: 'Markdown'
  end

  def start!(*)
    reply_with :message, text: t('hello')
  end

  def help!(*)
    respond_with :message, text: t('help', botname: Telegram.bot.username), parse_mode: 'Markdown'
  end

  private

  def change_title(message)
    chat = Chat.find(message.dig('chat', 'id'))
    chat.update(title: message['new_chat_title'])
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    user_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  protected

  def after_sign_out_path_for(_resource)
    root_path
  end

  def after_sign_in_path_for(_resource)
    user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to new_user_session_path
  end

  def show
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/views/connections/_connection.html.slim
.connection.row.mb-3
  .col-md-2.themed-grid-col
    .btn-group role="group"
      = link_to '🗙', user_connection_path(connection.user, connection),
                      method: :delete,
                      data: { turbo_method:'delete',turbo_confirm: t('.confirm') },
                      class: "btn btn-danger",
                      style: "opacity: 0.9"
      = link_to t('.edit'), edit_user_connection_path(connection.user, connection),
                        class: "btn btn-warning",
                        style: "opacity: 0.9"
  .col-md-4.themed-grid-col.my-auto.text-center
    = t('.telegram')
    |  "
    b
      = connection.chat.title
    | "
  .col-md-2.themed-grid-col.my-auto
    | —> 
  .col-md-4.themed-grid-col.my-auto
    = t('.jira')
    |  "
    b
      = connection.project_key
    | "

app/views/connections/_form.html.slim
= form_with(model: [@user, @connection]) do |f|
  .field
    = f.label :chat_id, t('.tg_group')
    = f.collection_select :chat_id,
                          @chats_collection,
                          :id,
                          :title,
                          { prompt: t('.select_chat') },
                          class: 'form-select'

  .field.mt-3
    = f.label :site, t('.jira_site')
    = f.text_field :site, class: "form-control", placeholder: 'https://your-domain.atlassian.net/'
  
  .field.mt-3
    = f.label :email, t('.jira_email')
    = f.email_field :email, class: "form-control", placeholder: 'johndoe@example.com'
  
  .field.mt-3
    = f.label :api_token, t('.jira_token')
    = f.text_field :api_token, class: "form-control"
  
  .field.mt-3
    = f.label :project_key, t('.jira_project')
    = f.text_field :project_key, class: "form-control", placeholder: 'PROJ'
  
  = f.submit t('.connect'), class: "w-50 btn btn-lg btn-success mx-auto mt-3", type: "submit"

- if @connection.errors.include?(:base)
  - @connection.errors.where(:base).each do |e|
    p
      | ❌
      =< e.full_message

app/views/connections/edit.html.slim
br
= link_to t('connections.new.back'), user_path(@user),
                                     class: "btn btn-danger"

.text-center.m-auto style="max-width: 500px"
  h2
    = t('.connection') 
  = render 'form', user: @user

app/views/connections/new.html.slim
br
= link_to t('.back'), user_path(@user),
                                     class: "btn btn-danger"

.text-center.m-auto style="max-width: 500px"
  h2
    = t('.connection') 

  = render 'form', user: @user

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Gefest
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

    = favicon_link_tag asset_path('favicon.ico')
  body
    - if user_signed_in?
      div.navbar.bg-dark
        div
          = image_tag("logos/logo.png", width: "50px", class: "ms-3")
          - if I18n.locale == :ru
            = link_to "🇺🇸", { :locale=>'en' }, class: "ms-3 text-decoration-none align-bottom"
          - else
            = link_to "🇷🇺", { :locale=>nil }, class: "ms-3 text-decoration-none align-bottom"

        div.btn-group role="group"
          b.my-auto.me-3
            = link_to current_user.email, user_path(current_user), class: "link-warning ms-3 align-middle me-2"
          = button_to t('.logout'), destroy_user_session_path, method: :delete, class: "btn btn-outline-danger rounded-pill me-2"

    p.notice style="color: green; margin-left: 10px"
      = notice
    p.alert
      = alert
    .container
      = yield

app/views/users/show.html.slim
h3
  = t('.connections')
.mx-auto.w-50.text-center
  = button_to t('.new_connection'), new_user_connection_path(@user),
                                    method: :get,
                                    class: "btn btn-outline-success",
                                    style: "min-width: 200px; opacity: 0.7"

- if @user.connections.empty?
  h4.text-center.mt-5
    = t('.start_bot')
    = link_to '@' + Telegram.bot.username, 'https://t.me/' + Telegram.bot.username,
                                            target: "_blank",
                                            class: "link-danger text-decoration-none"
    = t('.end_bot')

.mt-3
  = render @user.connections